#! /usr/bin/env bash

SRC=texinfo-6.7.tar.xz
DIR=texinfo-6.7

cd /tools-sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr > /dev/null
make -j8 -s > /dev/null
make install > /dev/null
