#! /bin/bash

SRC=bash-5.1.tar.gz
DIR=bash-5.1

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

sed -i  '/^bashline.o:.*shmbchar.h/a bashline.o: ${DEFDIR}/builtext.h' Makefile.in
./configure --prefix=/usr                    \
            --docdir=/usr/share/doc/bash-5.1 \
            --without-bash-malloc            \
            --with-installed-readline > /dev/null
make -j8 -s > /dev/null
chown -Rv tester .
su tester << EOF
PATH=$PATH make tests < $(tty)
EOF
make install > /dev/null
mv -vf /usr/bin/bash /bin
