#! /bin/bash

SRC=bc-3.3.0.tar.xz
DIR=bc-3.3.0

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

PREFIX=/usr CC=gcc ./configure.sh -G -O3 > /dev/null
make -j8 -s > /dev/null
make -j8 test
make install > /dev/null
