#! /bin/bash

SRC=binutils-2.36.1.tar.xz
DIR=binutils-2.36.1

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

expect -c "spawn ls"
sed -i '/@\tincremental_copy/d' gold/testsuite/Makefile.in

mkdir -v build
cd       build

../configure --prefix=/usr       \
             --enable-gold       \
             --enable-ld=default \
             --enable-plugins    \
             --enable-shared     \
             --disable-werror    \
             --enable-64-bit-bfd \
             --with-system-zlib > /dev/null
make -j8 tooldir=/usr > /dev/null
make -j8 -k check
make tooldir=/usr install > /dev/null
rm -fv /usr/lib/lib{bfd,ctf,ctf-nobfd,opcodes}.a
