#! /bin/bash

SRC=file-5.39.tar.gz
DIR=file-5.39

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr > /dev/null
make -j8 -s > /dev/null
make -j8 check 
make install > /dev/null
