#! /bin/bash

SRC=flex-2.6.4.tar.gz
DIR=flex-2.6.4

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr \
            --docdir=/usr/share/doc/flex-2.6.4 \
            --disable-static > /dev/null
make -j8 -s > /dev/null
make -j8 check
make install > /dev/null
ln -sv flex /usr/bin/lex
