#! /bin/bash

SRC=gettext-0.21.tar.xz
DIR=gettext-0.21

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/gettext-0.21 > /dev/null

make -j8 -s > /dev/null
make -j8 check
make install > /dev/null
chmod -v 0755 /usr/lib/preloadable_libintl.so
