#! /bin/bash

SRC=grep-3.6.tar.xz
DIR=grep-3.6

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr --bindir=/bin > /dev/null
make -j8 -s > /dev/null
make -j8 check > /dev/null
make install > /dev/null
