#! /bin/bash

SRC=less-563.tar.gz            
DIR=less-563

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr --sysconfdir=/etc > /dev/null
make -j8 -s > /dev/null
make install > /dev/null
