#! /bin/bash

SRC=pkg-config-0.29.2.tar.gz
DIR=pkg-config-0.29.2

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr              \
            --with-internal-glib       \
            --disable-host-tool        \
            --docdir=/usr/share/doc/pkg-config-0.29.2 > /dev/null

make -j8 -s > /dev/null
make -j8 check
make install > /dev/null
