#! /bin/bash

SRC=psmisc-23.4.tar.xz
DIR=psmisc-23.4

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr > /dev/null
make -j8 -s > /dev/null
make install > /dev/null

mv -v /usr/bin/fuser   /bin
mv -v /usr/bin/killall /bin
