#! /bin/bash

SRC=tar-1.34.tar.xz
DIR=tar-1.34

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

FORCE_UNSAFE_CONFIGURE=1  \
./configure --prefix=/usr \
            --bindir=/bin > /dev/null

make -j8 -s > /dev/null
make -j8 check
make install > /dev/null
make -j8 -C doc install-html docdir=/usr/share/doc/tar-1.34
