#! /bin/bash

SRC=XML-Parser-2.46.tar.gz
DIR=XML-Parser-2.46

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

perl Makefile.PL > /dev/null
make -j8 -s > /dev/null
make -j8 test
make install > /dev/null
