#! /usr/bin/env bash

SRC=diffutils-3.7.tar.xz
DIR=diffutils-3.7

cd $LFS/tools-sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr --host=$LFS_TGT > /dev/null
make -j8 -s > /dev/null
make DESTDIR=$LFS install > /dev/null
