#! /usr/bin/env bash

SRC=file-5.39.tar.gz
DIR=file-5.39

cd $LFS/tools-sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

mkdir build
cd build
cat > gcc.nix << "EOF"
with import <nixpkgs> {};
pkgs.mkShell {
    buildInputs = with pkgs; [ gcc ];
}
EOF
nix-shell gcc.nix --run "../configure --disable-bzlib --disable-libseccomp --disable-xzlib --disable-zlib > /dev/null"
nix-shell gcc.nix --run "make -j8 -s > /dev/null"
cd ..

./configure --prefix=/usr --host=$LFS_TGT --build=$(./config.guess) > /dev/null
make -j8 FILE_COMPILE=$(pwd)/build/src/file -s > /dev/null
make DESTDIR=$LFS install > /dev/null
