#! /usr/bin/env bash

SRC=binutils-2.36.1.tar.xz
DIR=binutils-2.36.1

cd $LFS/tools-sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC

cd $DIR
mkdir build
cd build
cat > gcc_with_options.nix << "EOF"
  with import <nixpkgs> {};
  pkgs.mkShell {
  buildInputs = with pkgs; [ gcc ];
  hardeningDisable = [ "format" ];
}
EOF

nix-shell gcc_with_options.nix --run "../configure --prefix=$LFS/tools --with-sysroot=$LFS --target=$LFS_TGT --disable-nls --disable-werror > /dev/null"
nix-shell gcc_with_options.nix --run "make -j8 -s > /dev/null"
make install > /dev/null
