#! /usr/bin/env bash

SRC=ncurses-6.2.tar.gz
DIR=ncurses-6.2

cd $LFS/tools-sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

sed -i s/mawk// configure

mkdir build
cd build
cat > gcc.nix << "EOF"
  with import <nixpkgs> {};
  pkgs.mkShell {
  buildInputs = with pkgs; [ gcc ];
}
EOF
nix-shell gcc.nix --run "../configure > /dev/null"
nix-shell gcc.nix --run "make -j8 -C include -s > /dev/null"
nix-shell gcc.nix --run "make -j8 -C progs tic -s > /dev/null"
cp gcc.nix ../.
cd ..


nix-shell gcc.nix --run \
"./configure --prefix=/usr                \
             --host=$LFS_TGT              \
             --build=$(./config.guess)    \
             --mandir=/usr/share/man      \
             --with-manpage-format=normal \
             --with-shared                \
             --without-debug              \
             --without-ada                \
             --without-normal             \
             --enable-widec               \
             CC=$LFS/tools/bin/x86_64-lfs-linux-gnu-gcc \
             CXX=$LFS/tools/bin/x86_64-lfs-linux-gnu-g++ > /dev/null"

nix-shell gcc.nix --run "make -j8 -s > /dev/null"
make DESTDIR=$LFS TIC_PATH=$(pwd)/build/progs/tic install > /dev/null
echo "INPUT(-lncursesw)" > $LFS/usr/lib/libncurses.so
mv -v $LFS/usr/lib/libncursesw.so.6* $LFS/lib
ln -sfv ../../lib/$(readlink $LFS/usr/lib/libncursesw.so) $LFS/usr/lib/libncursesw.so
