#! /usr/bin/env bash

SRC=gzip-1.10.tar.xz
DIR=gzip-1.10

cd $LFS/tools-sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR
./configure --prefix=/usr --host=$LFS_TGT
make -j8
make DESTDIR=$LFS install

exit
