#! /usr/bin/env bash

SRC=sed-4.8.tar.xz
DIR=sed-4.8

cd $LFS/tools-sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr   \
            --host=$LFS_TGT \
            --bindir=/bin
make -j8
make DESTDIR=$LFS install

exit
