#! /usr/bin/env bash

SRC=make-4.3.tar.gz
DIR=make-4.3

cd $LFS/tools-sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr   \
            --without-guile \
            --host=$LFS_TGT \
            --build=$(build-aux/config.guess) > /dev/null

make -j8 -s > /dev/null
make DESTDIR=$LFS install > /dev/null
