#! /usr/bin/env bash

SRC=gzip-1.10.tar.xz
DIR=gzip-1.10

cd $LFS/tools-sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR
./configure --prefix=/usr --host=$LFS_TGT > /dev/null
make -j8 -s > /dev/null
make DESTDIR=$LFS install > /dev/null
