#! /usr/bin/env bash

SRC=linux-5.10.17.tar.xz
DIR=linux-5.10.17

cd $LFS/tools-sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

cat > gcc.nix << "EOF"
  with import <nixpkgs> {};
  pkgs.mkShell {
  buildInputs = with pkgs; [ gcc ];
}
EOF

nix-shell gcc.nix --run "make mrproper -s > /dev/null"
nix-shell gcc.nix --run "make headers -s > /dev/null"
find usr/include -name '.*' -delete
rm usr/include/Makefile
cp -r usr/include $LFS/usr
