#! /bin/bash

SRC=attr-2.4.48.tar.gz
DIR=attr-2.4.48

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr     \
            --disable-static  \
            --sysconfdir=/etc \
            --docdir=/usr/share/doc/attr-2.4.48 > /dev/null

make -j8 -s > /dev/null
make -j8 check
make install > /dev/null

mv -v /usr/lib/libattr.so.* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libattr.so) /usr/lib/libattr.so
