#! /bin/bash

SRC=autoconf-2.71.tar.xz
DIR=autoconf-2.71

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr > /dev/null
make -j8 -s > /dev/null
make -j8 check
make install > /dev/null
