#! /bin/bash

SRC=coreutils-8.32.tar.xz
DIR=coreutils-8.32

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

patch -Np1 -i ../coreutils-8.32-i18n-1.patch
sed -i '/test.lock/s/^/#/' gnulib-tests/gnulib.mk

autoreconf -fiv
FORCE_UNSAFE_CONFIGURE=1 ./configure \
            --prefix=/usr            \
            --enable-no-install-program=kill,uptime > /dev/null
make -j8 -s > /dev/null
make -j8 NON_ROOT_USERNAME=tester check-root
echo "dummy:x:102:tester" >> /etc/group

chown -Rv tester . 
su tester -c "PATH=$PATH make RUN_EXPENSIVE_TESTS=yes check"
sed -i '/dummy/d' /etc/group

make install ? /dev/null
mv  /usr/bin/{cat,chgrp,chmod,chown,cp,date,dd,df,echo} /bin
mv  /usr/bin/{false,ln,ls,mkdir,mknod,mv,pwd,rm} /bin
mv  /usr/bin/{rmdir,stty,sync,true,uname} /bin
mv  /usr/bin/chroot /usr/sbin
mv  /usr/share/man/man1/chroot.1 /usr/share/man/man8/chroot.8
sed -i 's/"1"/"8"/' /usr/share/man/man8/chroot.8
mv  /usr/bin/{head,nice,sleep,touch} /bin
