#! /bin/bash

SRC=libpipeline-1.5.3.tar.gz   
DIR=libpipeline-1.5.3

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr > /dev/null
make -j8 -s > /dev/null
make -j8 check
make install > /dev/null
