#! /bin/bash

SRC=meson-0.57.1.tar.gz
DIR=meson-0.57.1

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

python3 setup.py build
python3 setup.py install --root=dest
cp -rv dest/* /
