#! /bin/bash

SRC=readline-8.1.tar.gz
DIR=readline-8.1

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

sed -i '/MV.*old/d' Makefile.in
sed -i '/{OLDSUFF}/c:' support/shlib-install
./configure --prefix=/usr    \
            --disable-static \
            --with-curses    \
            --docdir=/usr/share/doc/readline-8.1 > /dev/null
make -j8 SHLIB_LIBS="-lncursesw" -s > /dev/null
make SHLIB_LIBS="-lncursesw" install > /dev/null

mv -v /usr/lib/lib{readline,history}.so.* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libreadline.so) /usr/lib/libreadline.so
ln -sfv ../../lib/$(readlink /usr/lib/libhistory.so ) /usr/lib/libhistory.so
install -v -m644 doc/*.{ps,pdf,html,dvi} /usr/share/doc/readline-8.1
