#! /bin/bash

SRC=texinfo-6.7.tar.xz
DIR=texinfo-6.7

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr > /dev/null
make -j8 -s > /dev/null
make -j8 check
make install > /dev/null
make TEXMF=/usr/share/texmf install-tex > /dev/null
pushd /usr/share/info
  rm -v dir
  for f in *
    do install-info $f dir 2>/dev/null
  done
popd
