#! /bin/bash

SRC=zlib-1.2.11.tar.xz
DIR=zlib-1.2.11

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr  > /dev/null
make -j8 -s > /dev/null
make check
make install > /dev/null
mv -v /usr/lib/libz.so.* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libz.so) /usr/lib/libz.so
rm -fv /usr/lib/libz.a
