#! /bin/bash

SRC=ninja-1.10.2.tar.gz
DIR=ninja-1.10.2

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

export NINJAJOBS=8

sed -i '/int Guess/a \
  int   j = 0;\
  char* jobs = getenv( "NINJAJOBS" );\
  if ( jobs != NULL ) j = atoi( jobs );\
  if ( j > 0 ) return j;\
' src/ninja.cc
python3 configure.py --bootstrap > /dev/null

./ninja ninja_test > /dev/null
./ninja_test --gtest_filter=-SubprocessTest.SetWithLots
install -m755 ninja /usr/bin/
install -Dm644 misc/bash-completion /usr/share/bash-completion/completions/ninja
install -Dm644 misc/zsh-completion  /usr/share/zsh/site-functions/_ninja

unset NINJAJOBS
