#! /bin/bash

SRC=findutils-4.8.0.tar.xz
DIR=findutils-4.8.0

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr --localstatedir=/var/lib/locate > /dev/null
make -j8 -s > /dev/null
chown -Rv tester .
su tester -c "PATH=$PATH make -j8 check"
make install > /dev/null
mv -v /usr/bin/find /bin
sed -i 's|find:=${BINDIR}|find:=/bin|' /usr/bin/updatedb
