#! /bin/bash

SRC=dejagnu-1.6.2.tar.gz
DIR=dejagnu-1.6.2

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr > /dev/null
makeinfo --html --no-split -o doc/dejagnu.html doc/dejagnu.texi > /dev/null
makeinfo --plaintext       -o doc/dejagnu.txt  doc/dejagnu.texi > /dev/null
make install > /dev/null
install -v -dm755  /usr/share/doc/dejagnu-1.6.2
install -v -m644   doc/dejagnu.{html,txt} /usr/share/doc/dejagnu-1.6.2
make -j8 check
