#! /bin/bash

SRC=m4-1.4.18.tar.xz           
DIR=m4-1.4.18

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

sed -i 's/IO_ftrylockfile/IO_EOF_SEEN/' lib/*.c
echo "#define _IO_IN_BACKUP 0x100" >> lib/stdio-impl.h

./configure --prefix=/usr > /dev/null
make -j8 -s > /dev/null
make -j8 check
make install > /dev/null
