#! /bin/bash

SRC=zstd-1.4.8.tar.gz
DIR=zstd-1.4.8

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

make -j8 -s > /dev/null
make -j8 check
make prefix=/usr install > /dev/null

rm -v /usr/lib/libzstd.a
mv -v /usr/lib/libzstd.so.* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libzstd.so) /usr/lib/libzstd.so
