#! /bin/bash

SRC=sed-4.8.tar.xz
DIR=sed-4.8

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr --bindir=/bin > /dev/null

make -j8 -s > /dev/null
make -j8 html -s > /dev/null

chown -Rv tester .
su tester -c "PATH=$PATH make check"
make install > /dev/null
install -d -m755           /usr/share/doc/sed-4.8
install -m644 doc/sed.html /usr/share/doc/sed-4.8
