#! /bin/bash

SRC=expat-2.2.10.tar.xz
DIR=expat-2.2.10

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR
./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/expat-2.2.10 > /dev/null

make -j8 -s > /dev/null
make -j8 check
make install > /dev/null

install -v -m644 doc/*.{html,png,css} /usr/share/doc/expat-2.2.10
