#! /bin/bash

SRC=gperf-3.1.tar.gz
DIR=gperf-3.1

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr --docdir=/usr/share/doc/gperf-3.1 > /dev/null
make -j8 -s > /dev/null
make -j1 check
make install > /dev/null

