#! /usr/bin/env bash

./scripts/build_binutils_1
./scripts/build_gcc_1
./scripts/install_linux_header
./scripts/build_glibc
./scripts/build_libstdc++_1
./scripts/build_m4
./scripts/build_ncurses
./scripts/build_bash
./scripts/build_coreutils
./scripts/build_diffutils
./scripts/build_file
./scripts/build_findutils
./scripts/build_gawk
./scripts/build_grep
./scripts/build_gzip
./scripts/build_make
./scripts/build_patch
./scripts/build_sed
./scripts/build_tar
./scripts/build_xz
./scripts/build_binutils_2
./scripts/build_gcc_2
