#! /usr/bin/env bash


cd $LFS/tools-sources && find . -name "*.xz" | xargs -n 1 tar Jxf
cd $LFS/tools-sources && find . -name "*.gz" | xargs -n 1 tar zxf

cd $LFS/tools-sources && cp -r gcc-10.2.0 gcc-10.2.0-1
cd $LFS/tools-sources && cp -r gcc-10.2.0 gcc-10.2.0-2
cd $LFS/tools-sources && cp -r gcc-10.2.0 gcc-10.2.0-3
cd $LFS/tools-sources && cp -r binutils-2.36.1 binutils-2.36.1-1
