#! /usr/bin/env bash

cat > ~/.bash_profile << "EOF"
exec env -i HOME=$HOME TERM=$TERM PS1='\u:\w\$ ' bash
EOF
cat > ~/.bashrc << "EOF"
set +h
umask 022
LFS=/mnt/lfs
LC_ALL=POSIX
LFS_TGT=$(uname -m)-lfs-linux-gnu
PATH=/usr/bin
if [ ! -L /bin ]; then PATH=/bin:$PATH; fi
PATH=/run/current-system/sw/bin:$PATH
PATH=$HOME/.nix-profile/bin:$PATH
PATH=$LFS/tools/bin:$PATH
CONFIG_SITE=$LFS/usr/share/config.site/run/current-system/sw/bin
export LFS LC_ALL LFS_TGT PATH CONFIG_SITE
EOF

cd $LFS/tools-sources && find . -name "*.xz" | xargs -n 1 tar Jxf
cd $LFS/tools-sources && find . -name "*.gz" | xargs -n 1 tar zxf

cd $LFS/tools-sources && cp -r gcc-10.2.0 gcc-10.2.0-1
cd $LFS/tools-sources && cp -r gcc-10.2.0 gcc-10.2.0-2
cd $LFS/tools-sources && cp -r gcc-10.2.0 gcc-10.2.0-3
cd $LFS/tools-sources && cp -r binutils-2.36.1 binutils-2.36.1-1
