#! /bin/bash

SRC=dejagnu-1.6.2.tar.gz
DIR=dejagnu-1.6.2

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr 
makeinfo --html --no-split -o doc/dejagnu.html doc/dejagnu.texi 
makeinfo --plaintext       -o doc/dejagnu.txt  doc/dejagnu.texi 
make install 
install -dm755 /usr/share/doc/dejagnu-1.6.2
install -m644  doc/dejagnu.{html,txt} /usr/share/doc/dejagnu-1.6.2
