#! /bin/bash

SRC=expect5.45.4.tar.gz
DIR=expect5.45.4

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR
./configure --prefix=/usr           \
            --with-tcl=/usr/lib     \
            --enable-shared         \
            --mandir=/usr/share/man \
            --with-tclinclude=/usr/include 
make
make install 
ln -sf expect5.45.4/libexpect5.45.4.so /usr/lib
