#! /bin/bash

SRC=xz-5.2.5.tar.xz
DIR=xz-5.2.5

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/xz-5.2.5 
make
make install 
mv  /usr/bin/{lzma,unlzma,lzcat,xz,unxz,xzcat} /bin
mv  /usr/lib/liblzma.so.* /lib
ln -sf ../../lib/$(readlink /usr/lib/liblzma.so) /usr/lib/liblzma.so
