#! /usr/bin/env bash

SRC=gettext-0.21.tar.xz
DIR=gettext-0.21

cd /tools-sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --disable-shared > /dev/null
make -j8 -s > /dev/null
cp -v gettext-tools/src/{msgfmt,msgmerge,xgettext} /usr/bin
