#! /usr/bin/env bash

SRC=bash-5.1.tar.gz
DIR=bash-5.1

cd $LFS/tools-sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

cat > gcc.nix << "EOF"
  with import <nixpkgs> {};
  pkgs.mkShell {
  buildInputs = with pkgs; [ gcc ];
  shellHook = '' 
    export PATH="$LFS/tools/bin:$PATH"
    unset CC
  '';
}
EOF

nix-shell gcc.nix --run \
"./configure --prefix=/usr                  \
             --build=$(support/config.guess) \
             --host=$LFS_TGT                 \
             --without-bash-malloc"

          #   BUILD_FOR_CC=gcc                \
          #   CC=$LFS/tools/bin/x86_64-lfs-linux-gnu-gcc"
nix-shell gcc.nix --run "make"
nix-shell gcc.nix --run "make DESTDIR=$LFS install"
mv $LFS/usr/bin/bash $LFS/bin/bash
ln -s bash $LFS/bin/sh
