#! /usr/bin/env bash

SRC=binutils-2.36.1.tar.xz
DIR=binutils-2.36.1

cd $LFS/tools-sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC

cd $DIR
mkdir build
cd build

cat > gcc_with_options.nix << "EOF"
with import <nixpkgs> {};
pkgs.mkShell {
    buildInputs = with pkgs; [ gcc ];
    hardeningDisable = [ "format" ];
}
EOF

../configure                   \
    --prefix=/usr              \
    --build=$(../config.guess) \
    --host=$LFS_TGT            \
    --disable-nls              \
    --enable-shared            \
    --disable-werror           \
    --enable-64-bit-bfd

nix-shell gcc_with_options.nix --run "make"
make DESTDIR=$LFS install 
install -vm755 libctf/.libs/libctf.so.0.0.0 $LFS/usr/lib
