#! /usr/bin/env bash

SRC=xz-5.2.5.tar.xz
DIR=xz-5.2.5

cd $LFS/tools-sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr                     \
            --host=$LFS_TGT                   \
            --build=$(build-aux/config.guess) \
            --disable-static                  \
            --docdir=/usr/share/doc/xz-5.2.5 
make
make DESTDIR=$LFS install 

mv $LFS/usr/bin/{lzma,unlzma,lzcat,xz,unxz,xzcat}  $LFS/bin
mv $LFS/usr/lib/liblzma.so.*                       $LFS/lib
ln -sf ../../lib/$(readlink $LFS/usr/lib/liblzma.so) $LFS/usr/lib/liblzma.so
