#! /usr/bin/env bash

export LFS=/mnt/lfs

losetup -P /dev/loop0 lfs.img 
mount -v -t ext4 /dev/loop0p1 $LFS

chown -v lfs $LFS/{usr,lib,var,etc,bin,sbin,tools,lib64}
chown -v lfs $LFS/{sources,tools-sources}

cat > /home/lfs/.bash_profile << "EOF"
exec env -i HOME=$HOME TERM=$TERM PS1='\u:\w\$ ' bash
EOF
cat > /home/lfs/.bashrc << "EOF"
set +h
umask 022
LFS=/mnt/lfs
LC_ALL=POSIX
LFS_TGT=$(uname -m)-lfs-linux-gnu
PATH=/usr/bin
if [ ! -L /bin ]; then PATH=/bin:$PATH; fi
PATH=/run/current-system/sw/bin:$PATH
PATH=$HOME/.nix-profile/bin:$PATH
PATH=$LFS/tools/bin:$PATH
CONFIG_SITE=$LFS/usr/share/config.site/run/current-system/sw/bin
export LFS LC_ALL LFS_TGT PATH CONFIG_SITE
EOF

chmod -v lfs:users /home/lfs/{.bash_profile,.bashrc}

umount -v /dev/loop0p1
losetup -d /dev/loop0
