#! /usr/bin/env bash

qemu-img create -f raw lfs.img 60G

parted lfs.img -- mklabel gpt
parted lfs.img -- mkpart primary 512MiB -8GiB
parted lfs.img -- mkpart primary linux-swap -8GiB 100%
parted lfs.img -- mkpart ESP fat32 1MiB 512MiB
parted lfs.img -- set 3 esp on

losetup -P /dev/loop0 lfs.img 
mkfs.ext4 -L lfs /dev/loop0p1
mkswap -L swap /dev/loop0p2
mkfs.fat -F 32 -n boot /dev/loop0p3
losetup -d /dev/loop0

losetup -P /dev/loop0 lfs.img 
mount -v -t ext4 /dev/loop0p1 /mnt/lfs
swapon -v /dev/loop0p2

mkdir -pv /mnt/lfs/{bin,etc,lib,sbin,usr,var,lib64}
mkdir -pv /mnt/lfs/tools

mkdir -v /mnt/lfs/sources
chmod -v a+wt /mnt/lfs/sources
wget http://lfsbookja.osdn.jp/10.1-sysdja/wget-list
cat > wl.sed << "EOF"
s|ftp\.gnu\.org/gnu/|ftp.riken.jp/GNU/|g
s|https://www\.kernel\.org/pub/linux/|http://ftp.riken.jp/Linux/kernel.org/linux/|g
s|www\.cpan\.org|ftp.riken.jp/lang/CPAN|g
s|ftp\.vim\.org|ftp.jp.vim.org|g
EOF
sed -f wl.sed -i.orig wget-list 
rm wl.sed 
wget -N --input-file=wget-list --continue --directory-prefix=/mnt/lfs/sources
wget -N --input-file=wget-list.orig --continue --directory-prefix=/mnt/lfs/sources
rm wget-list wget-list.orig

wget http://lfsbookja.osdn.jp/10.1-sysdja/md5sums
mv md5sums /mnt/lfs/sources/.
cd /mnt/lfs/sources
md5sum -c md5sums
rm md5sums

mkdir /mnt/lfs/tools-sources
chmod -v a+wt /mnt/lfs/tools-sources
cat > /mnt/lfs/tools-sources/tools-list << "EOF"
gcc-10.2.0.tar.xz
binutils-2.36.1.tar.xz
glibc-2.33.tar.xz 
glibc-2.33-fhs-1.patch 
linux-5.10.17.tar.xz
util-linux-2.36.2.tar.xz
m4-1.4.18.tar.xz
ncurses-6.2.tar.gz
bash-5.1.tar.gz
coreutils-8.32.tar.xz
coreutils-8.32-i18n-1.patch
diffutils-3.7.tar.xz 
file-5.39.tar.gz 
findutils-4.8.0.tar.xz
gawk-5.1.0.tar.xz
grep-3.6.tar.xz 
gzip-1.10.tar.xz
make-4.3.tar.gz
patch-2.7.6.tar.xz
Python-3.9.2.tar.xz
sed-4.8.tar.xz
tar-1.34.tar.xz
xz-5.2.5.tar.xz
gettext-0.21.tar.xz
bison-3.7.5.tar.xz
perl-5.32.1.tar.xz
texinfo-6.7.tar.xz
EOF
cd /mnt/lfs/sources && cat ../tools-sources/tools-list | xargs cp -t ../tools-sources

chown -v lfs /mnt/lfs/{usr,lib,var,etc,bin,sbin,tools,lib64}
chown -v lfs /mnt/lfs/sources
chown -v lfs /mnt/lfs/tools-sources


