#! /bin/bash

SRC=attr-2.4.48.tar.gz
DIR=attr-2.4.48

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr     \
            --disable-static  \
            --sysconfdir=/etc \
            --docdir=/usr/share/doc/attr-2.4.48

make
make install

mv /usr/lib/libattr.so.* /lib
ln -sf ../../lib/$(readlink /usr/lib/libattr.so) /usr/lib/libattr.so
