#! /bin/bash

SRC=mpfr-4.1.0.tar.xz
DIR=mpfr-4.1.0

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr        \
            --disable-static     \
            --enable-thread-safe \
            --docdir=/usr/share/doc/mpfr-4.1.0 

make
make html
make install 
make install-html 
