#! /bin/bash

SRC=findutils-4.8.0.tar.xz
DIR=findutils-4.8.0

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr --localstatedir=/var/lib/locate 
make
make install 
mv -v /usr/bin/find /bin
sed -i 's|find:=${BINDIR}|find:=/bin|' /usr/bin/updatedb
