#! /bin/bash

SRC=gawk-5.1.0.tar.xz
DIR=gawk-5.1.0

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

sed -i 's/extras//' Makefile.in
./configure --prefix=/usr 
make
make install 
mkdir -v /usr/share/doc/gawk-5.1.0
cp    -v doc/{awkforai.txt,*.{eps,pdf,jpg}} /usr/share/doc/gawk-5.1.
