#! /bin/bash

SRC=gdbm-1.19.tar.gz
DIR=gdbm-1.19

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr    \
            --disable-static \
            --enable-libgdbm-compat 
make
make install 
