#! /bin/bash

SRC=gettext-0.21.tar.xz
DIR=gettext-0.21

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/gettext-0.21 
make
make install 
chmod -v 0755 /usr/lib/preloadable_libintl.so
