#! /bin/bash

SRC=grub-2.04.tar.xz
DIR=grub-2.04

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

sed "s/gold-version/& -R .note.gnu.property/" \
    -i Makefile.in grub-core/Makefile.in

./configure --prefix=/usr          \
            --sbindir=/sbin        \
            --sysconfdir=/etc      \
            --disable-efiemu       \
            --disable-werror 
make
make install 
mv /etc/bash_completion.d/grub /usr/share/bash-completion/completions
