#! /bin/bash

SRC=psmisc-23.4.tar.xz
DIR=psmisc-23.4

cd /sources

if [ -d $DIR ]; then
  rm -rf $DIR
fi

tar -xf $SRC
cd $DIR

./configure --prefix=/usr 
make
make install 

mv -v /usr/bin/fuser   /bin
mv -v /usr/bin/killall /bin
